# Generated by Django 3.1.1 on 2021-10-24 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorizado',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='PhoneUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPhone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backApp.phone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
