# Generated by Django 3.1.1 on 2021-11-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0004_order_mot_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotDeviceRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDevice', models.CharField(max_length=50, verbose_name='Device ID')),
                ('idMot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backApp.motorizado')),
            ],
        ),
    ]
