# Generated by Django 3.1.1 on 2021-11-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0005_motdeviceregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='reg_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='motdeviceregister',
            name='idDevice',
            field=models.TextField(verbose_name='Device ID'),
        ),
    ]
