# Generated by Django 3.1.1 on 2021-12-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0006_auto_20211122_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercomments',
            name='grade',
            field=models.FloatField(null=True, verbose_name='Delivery grading'),
        ),
    ]
