# Generated by Django 3.1.1 on 2021-12-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0007_auto_20211206_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='map_id',
        ),
        migrations.AddField(
            model_name='local',
            name='nombre_mapa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Name of the map'),
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
