# Generated by Django 3.1.1 on 2022-01-20 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0008_auto_20211208_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backApp.client')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backApp.location')),
            ],
        ),
    ]
