# Generated by Django 3.1.1 on 2021-08-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvehicle',
            name='color',
            field=models.CharField(max_length=15, unique=True, verbose_name='Color of car'),
        ),
        migrations.AlterField(
            model_name='modelsvehicle',
            name='model',
            field=models.CharField(max_length=15, unique=True, verbose_name='Model of vehicle'),
        ),
        migrations.AlterField(
            model_name='typevehicle',
            name='type_vehicle',
            field=models.CharField(max_length=15, unique=True, verbose_name='Type of vehicle'),
        ),
    ]
