# Generated by Django 3.2.6 on 2021-08-09 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=10, verbose_name='id number of Client')),
                ('name', models.CharField(max_length=50, verbose_name='Client name')),
                ('apellido', models.CharField(max_length=50, verbose_name='Client last name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Client email')),
            ],
        ),
        migrations.CreateModel(
            name='MotRegistComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment about the error in register')),
            ],
        ),
        migrations.CreateModel(
            name='MotValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorizado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Motorizado', to='backApp.motorizado')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=100, verbose_name='Details of the order')),
                ('price', models.FloatField(verbose_name='Order price')),
                ('delivery_price', models.FloatField(verbose_name='Delivery price')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Date and hour that the order is received by us')),
                ('mot_assigned_time', models.DateTimeField(verbose_name='Time the order has been assigned to a motorizado')),
                ('deliv_start_time', models.DateTimeField(verbose_name='Time the order begins its delivery')),
                ('arriv_estimated_time', models.DateTimeField(verbose_name='Arrival Estimated Time')),
                ('real_arriv_time', models.DateTimeField(verbose_name='Real arrival time')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backApp.client')),
                ('destiny_loc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backApp.location')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backApp.local')),
                ('motorizado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrderMotorizado', to='backApp.motorizado')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comments about the delivery of the order')),
                ('grade', models.FloatField(verbose_name='Delivery grading')),
                ('idOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=50, verbose_name='Type of payment')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pho_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backApp.client')),
                ('idPhone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backApp.phone')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPhone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backApp.phone')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backApp.local')),
            ],
        ),
        migrations.CreateModel(
            name='RegErrorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Error type')),
            ],
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/'),
        ),
        migrations.AddField(
            model_name='order',
            name='operador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrderOperador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motvalidation',
            name='operador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Operador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motregistcomments',
            name='error',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backApp.regerrortype'),
        ),
        migrations.AddField(
            model_name='motregistcomments',
            name='validation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backApp.motvalidation'),
        ),
    ]
