# Generated by Django 3.1.1 on 2021-08-14 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backApp.colorvehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backApp.typevehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='veh_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backApp.modelsvehicle'),
        ),
    ]
