# Generated by Django 3.1.1 on 2021-10-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0002_auto_20211024_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorizado',
            name='connected',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
