# Generated by Django 3.1.1 on 2021-08-18 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0002_auto_20210814_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorizado',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
