# Generated by Django 3.1.1 on 2021-11-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0003_motorizado_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mot_paid',
            field=models.BooleanField(default=False, verbose_name='Is paid to the motorizado'),
        ),
    ]
